In [2]:
print("Adaline Learning for AND,OR,XOR gate")

Adaline Learning for AND,OR,XOR gate


In [3]:
import numpy as np
def perceptron(inpt,t): 
    Error=100                  #Initial Non-zero error
    a=0.1                      #Taking learning rate as 0.1
    inpt=np.array(inpt)   
    t=np.array(t)
    W=np.random.rand(3)        #Generating random weights
    itr1=0                     #creating bound parameter for number of iterations
    while Error!=0:
        itr=0
        Error=0
        for x in inpt:
            O=W*(x)
            O=np.sum(O)
            dW=a*(t[itr]-O)*x
            Error+=np.sum(np.square(t[itr]-O))                #calculating error
            W=W+dW                                            #updating weight using stochastic method
            itr+=1
        itr1+=1
        if(itr1==100000):
            break
    print(W)
    print(Error)
        
            
    

In [8]:
#Adaline learning for OR gate
inpt=[[1,0,0],[1,0,1],[1,1,1],[1,1,0]]
t=[0,1,1,1]
perceptron(inpt,t)

[0.27777778 0.5        0.47222222]
0.308641975308642


In [9]:
#Adaline Learning  for AND gate
inpt=[[1,0,0],[1,0,1],[1,1,1],[1,1,0]]
t=[0,0,1,0]
perceptron(inpt,t)

[-0.27777778  0.5         0.52777778]
0.30864197530864196


In [10]:
#Adaline Learning for XOR gate
inpt=[[1,0,0],[1,0,1],[1,1,1],[1,1,0]]
t=[0,1,0,1]
perceptron(inpt,t)

[ 5.55555556e-01  3.33066907e-16 -5.55555556e-02]
1.2345679012345678
